name: API CI/CD

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install ruff
      - run: ruff check ./API
  unit-tests:
    name: Running unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install pytest
      - run: cd API && pytest tests
  unit-tests-coverage:
    name: Checking unit tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install coverage
      - run: pip install pytest-cov
      - run: |
          coverage_output=$(pytest --cov=. --cov-report=term | grep TOTAL | awk 'NF>1{print substr($NF,1,length($NF)-1)}')
          echo "Coverage: $coverage_output"

          coverage_int=${coverage_output%.*}

          if [ "$coverage_int" -lt 70 ]; then
            echo "Coverage too low: $coverage_output% (minimum is 70%)"
            exit 1
          else
            echo "Coverage OK: $coverage_output%"
          fi
